### ISSUE TITLE
New tile release based on agent version 7.40.0

### ISSUE THREAD

**Issue by basiszwo** [DataDog/datadog-application-monitoring-pivotal-tile#36]
Lately the agent got a new release with [version 7.40.0](https://github.com/DataDog/datadog-agent/releases/tag/7.40.0) which is long awaited in my company. 

The new agent version hopefully includes a fix correctly tagging apm traces with the CloudFoundry application instance id.

It would be great to see a new tile release. I guess a new buildpack release has to be made as well. I also [filed an issue in the buildpack repository](https://github.com/DataDog/datadog-cloudfoundry-buildpack/issues/138).

Can I help with anything? Please let me know.

Thank you very much!

**Comment by NouemanKHAL** [comment]
Hi @basiszwo.

The tile has been released : https://network.pivotal.io/products/datadog-application-monitoring#/releases/1204860

Regards
